### ISSUE TITLE
version issue for extension on mac 

### ISSUE THREAD

**Issue by shell11d** [joelspadin-garmin/vscode-private-extension-manager#44] opened 2021-04-09 19:47 UTC
The private manager works perfectly okay on linux but on mac when I have an older version of my extension installed through command palette install vsix option example: myExtension-0.0.7 the private manager shows myExtension-0.0.11 installed which is the latest but the actual extension is old. Also when I try to switch version using private manager it still shows  myExtension-0.0.11 installed but is not the latest. 

So private manager by default shows the latest version of the extension on mac but the actual extension version when used is not the latest. 

Let me know if more information is needed.

**Comment by joelspadin-garmin** [comment] 2021-04-09 19:59
Does it continue to show the wrong version even after reloading the window or restarting VS Code? 

Private Extension Manager is supposed to update extension info when extensions change https://github.com/joelspadin-garmin/vscode-private-extension-manager/blob/7abdbb9cb8f78bee487cf500e3b02b77eee9843e/extension/src/extensionInfo.ts#L123 but in my experience VS Code does not reliably fire that event when installing a different version of an already installed extension, and the extension info it reports may be out of date until you reload the window.

**Comment by shell11d** [comment] 2021-04-09 22:37
yes even after reload it continues showing the extension as latest on private manager but actual installed version is 0.0.7 

Basically if I have a version 0.0.7 installed through the install vsix command private manager shows it as installed lateste version it has a tick mark already and when I try to reload it keeps showing latest version on private manager when I switch versions it still shows latest on private manager so irrespective of what actual version I have the private manager shows it as latest. 


the workaround is I need to uninstall on private manager and the install again and reload that works 

This only happens on mac on Linux it shows the install 0.0.11 version on mac it only shows the install button without version from ui perspective.

**Comment by joelspadin-garmin** [comment] 2021-04-09 23:02
The private extension should also show up in the regular extensions panel. Does that show the correct version or does that also show the wrong version?

**Comment by shell11d** [comment] 2021-04-10 00:17
in the regular panel it shows the wrong version which I have installed through vsix which is the older one but with that version installed private manager shows 0.0.11 version installed with a tick mark. Ideally it should show update to latest on private manager? 

When I uninstall directly from regular extension the extension 0.0.11 in private manager gets uninstalled too so its like 0.0.7 is connected to 0.0.11 in private manager

**Comment by shell11d** [comment] 2021-04-10 00:19
also in mac i do not know if the private manager is being able to distinguish the versions like Linux. Looks like some piece of code is missing between Linux and mac since the UI is different for both

**Comment by shell11d** [comment] 2021-04-12 20:58
let me know if you need more info

**Comment by joelspadin-garmin** [comment] 2021-04-13 14:41
Assuming I correctly understand you, then it sounds like this is a bug in VS Code, not Private Extension Manager. When Private Extension Manager installs or updates an extension, it goes through exactly the same code as the "Extensions: Install from VSIX" command. If the regular panel shows the wrong version as well when you install directly from VSIX, then my best guess is that VS Code is not properly installing version 0.0.7 and is leaving 0.0.11 installed.

**Comment by denielig** [comment] 2021-09-15 13:56
Hi,
I have the same problem in Windows.
I think the problem is when a new version is deployed with one more digit. Example : 0.0.9 to 0.0.10 or 0.9.9 to 0.10.9
Maybe there is an alphabetical sort because 0.0.9 is upper to 0.0.10 ?

**Comment by denielig** [comment] 2021-09-15 14:44
I confirm. 
The problem is in the method isUpdateAvailable from the class Package. 
`this.version > this.installedVersion`
The comparison is between 2 strings (not 2 numbers). 
'0.0.10' > '0.0.9' --> false

**Comment by joelspadin-garmin** [comment] 2021-09-15 14:52
Those should be SemVer objects, not strings, but JavaScript doesn't allow operator overloading so it's possible it might be implicitly converting the objects to strings before doing the comparison. I think that needs to be `this.version.gt(this.installedVersion)`

**Comment by denielig** [comment] 2021-09-15 15:10
I just checked, it's well SemVer objects but `this.version > this.installedVersion` return false 
It's easy to fix : `return !!this.installedVersion && this.version.compare(this.installedVersion) == 1;`
Do you want a Pull Request or you want to fix it yourself ?

**Comment by joelspadin-garmin** [comment] 2021-12-15 16:24
Fixed in #59

**Closed by joelspadin-garmin** 2021-12-15 16:24 UTC
